language: c
addons:
  apt:
    sources:
    # - ubuntu-toolchain-r-test
    packages:
    - intltool
    # - gcc-4.9
    # http://wiki.mate-desktop.com/building
    # - 
install:
- wget http://pub.mate-desktop.org/releases/1.19/atril-1.19.4.tar.xz
- tar --xz --extract --file=atril-1.19.4.tar.xz
- ls
- cd atril-1.19.4
- apt-cache policy intltool

# atril-1.19.4
