language: c
addons:
  apt:
    sources:
    # - ubuntu-toolchain-r-test
    packages:
    # as requested by configure
    - intltool
    - libgtk-3-dev
    - libgio2.0-cil-dev
    # - gcc-4.9
    # http://wiki.mate-desktop.com/building
    # - 
install:
- wget http://pub.mate-desktop.org/releases/1.19/atril-1.19.4.tar.xz
- tar --xz --extract --file=atril-1.19.4.tar.xz
- ls
- cd atril-1.19.4
- apt-cache policy libgtk-3-dev libgio2.0-cil-dev

# atril-1.19.4
