language: c
addons:
  apt:
    sources:
    # - ubuntu-toolchain-r-test
    packages:
    # as requested by configure
    - intltool
    - libgtk-3-dev
    - libgio2.0-cil-dev
    # - gcc-4.9
    # http://wiki.mate-desktop.com/building
    # - 
install:
- wget http://pub.mate-desktop.org/releases/1.19/atril-1.19.0.tar.xz
- tar --xz --extract --file=atril-1.19.0.tar.xz
- ls
- cd atril-1.19.0
- apt-cache policy libgtk-3-dev libgio2.0-cil-dev
- ./configure --help

script:
- ./configure --with-gtk=2.0 && make && make test %% make install
# - env XDG_DATA_DIRS=/tmp/atril/share:/usr/share bin/atril file.pdf

# atril-1.19.4
# Package requirements (gtk+-3.0 >= 3.14.0 gio-2.0 >= 2.36.0)
#   Requested 'gtk+-3.0 >= 3.14.0' but version of GTK+ is 3.10.8
# On Ubuntu 16.03 outside Travis

