language: c
env:
- MATE=1.7 ATRIL=atril-1.7.90
# - MATE=1.19
# - ATRIL=atril-1.19.0
addons:
  apt:
    sources:
    # - ubuntu-toolchain-r-test
    packages:
    # as requested by configure
    - intltool
    - libgtk2.0-dev
    - libgail-dev
    # - libgtk-3-dev
    - libgio2.0-cil-dev
    # - gcc-4.9
    # http://wiki.mate-desktop.com/building
    # - 
install:
- wget http://pub.mate-desktop.org/releases/$MATE/$ATRIL.tar.xz
- tar --xz --extract --file=$ATRIL.tar.xz
- ls
- cd $ATRIL
- apt-cache policy libgtk2.0-dev libgio2.0-cil-dev
- ./configure --help

script:
- ./configure --with-gtk=2.0 && make && make test %% make install
# - env XDG_DATA_DIRS=/tmp/atril/share:/usr/share bin/atril file.pdf

# atril-1.19.4
# Package requirements (gtk+-3.0 >= 3.14.0 gio-2.0 >= 2.36.0)
#   Requested 'gtk+-3.0 >= 3.14.0' but version of GTK+ is 3.10.8
# On Ubuntu 16.03 outside Travis

